# Generated by Django 5.0.4 on 2025-03-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usertotpdevice_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTOTPDevice',
        ),
    ]
