# Generated by Django 5.0.4 on 2025-02-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
