# Generated by Django 5.0.4 on 2025-01-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
