# Generated by Django 5.0.4 on 2025-01-11 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='match_type',
        ),
        migrations.AddField(
            model_name='tournament',
            name='first_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place_tournaments', to='data.user'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='fourth_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth_place_tournaments', to='data.user'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='second_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place_tournaments', to='data.user'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='third_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place_tournaments', to='data.user'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
