# Generated by Django 5.0.4 on 2025-02-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='data/media/defaut.png', upload_to='data/media'),
        ),
    ]
