# Generated by Django 5.0.4 on 2025-04-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='friend',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='user',
            new_name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('sender', 'receiver')},
        ),
    ]
