# Generated by Django 5.0.4 on 2025-02-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_match_match_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='data/images/defaut.png', upload_to='./images'),
        ),
    ]
