# Generated by Django 5.0.4 on 2025-03-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_customuser_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
