# Generated by Django 5.0.4 on 2025-02-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
