# Generated by Django 5.0.4 on 2025-02-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='app/data/images/defaut.png', upload_to='./images'),
        ),
    ]
