# Generated by Django 5.0.4 on 2025-04-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_friend_friendship_receiver_and_more'),
        ('data', '0003_customuser_otp_secret'),
    ]

    operations = [
    ]
