# Generated by Django 5.0.4 on 2025-04-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_merge_20250404_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='confirmed_ready',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='status',
        ),
    ]
