# Generated by Django 5.0.4 on 2025-04-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_tournament_confirmed_ready_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_secret',
        ),
    ]
