# Generated by Django 5.0.4 on 2025-02-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
