# Generated by Django 5.0.4 on 2025-04-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_customuser_location_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('player_1', 'player_2', 'tournament')},
        ),
    ]
