# Generated by Django 5.0.4 on 2025-02-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
