# Generated by Django 5.0.4 on 2025-04-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_match_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
    ]
