# Generated by Django 5.0.4 on 2025-05-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_match_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('fr', 'French')], default='en', max_length=10, verbose_name='Preferred Language'),
        ),
    ]
