# Generated by Django 5.0.4 on 2025-05-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_customuser_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('fr', 'French')], default='en', max_length=10),
        ),
    ]
