# Generated by Django 5.0.4 on 2024-12-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking_service', '0004_alter_playerqueue_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerqueue',
            name='player_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
